DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS reward;

CREATE TABLE player(
	player_id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	level INT NOT NULL
);

CREATE TABLE reward(
	reward_id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	player_id INT NOT NULL
);
